// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtx2j8a7Of1ip6cMBl6ib459yHArACU78',
    appId: '1:54854471720:android:85733fd9ba80eba8ff651d',
    messagingSenderId: '54854471720',
    projectId: 'gestionpersonal-73b54',
    databaseURL: 'https://gestionpersonal-73b54.firebaseio.com',
    storageBucket: 'gestionpersonal-73b54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYg4TRnyI3D0irN1Kke3I_h6-EL192Ek4',
    appId: '1:54854471720:ios:aac92c9fbe8917e0ff651d',
    messagingSenderId: '54854471720',
    projectId: 'gestionpersonal-73b54',
    databaseURL: 'https://gestionpersonal-73b54.firebaseio.com',
    storageBucket: 'gestionpersonal-73b54.firebasestorage.app',
    iosBundleId: 'com.example.logisticaReparto',
  );
}
